// Generated by CoffeeScript 1.9.0
(function() {
  var Swipe,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = Swipe = (function() {
    function Swipe() {
      this.handleTouchMove = __bind(this.handleTouchMove, this);
      this.handleTouchStart = __bind(this.handleTouchStart, this);
    }

    Swipe.prototype.view = __dirname;

    Swipe.prototype.name = 'k-swipe';

    Swipe.prototype.xDown = null;

    Swipe.prototype.yDown = null;

    Swipe.prototype.init = function() {
      return this.model.set('hide', !this.model.get('show'));
    };

    Swipe.prototype.create = function() {
      document.addEventListener('touchstart', this.handleTouchStart, false);
      return document.addEventListener('touchmove', this.handleTouchMove, false);
    };

    Swipe.prototype.handleTouchStart = function(e) {
      var _ref, _ref1, _ref2, _ref3;
      this.xDown = (_ref = e.touches) != null ? (_ref1 = _ref[0]) != null ? _ref1.clientX : void 0 : void 0;
      this.yDown = (_ref2 = e.touches) != null ? (_ref3 = _ref2[0]) != null ? _ref3.clientY : void 0 : void 0;
    };

    Swipe.prototype.handleTouchMove = function(e) {
      var xDiff, xUp, yDiff, yUp;
      if (!this.xDown || !this.yDown || !e.touches) {
        return;
      }
      xUp = e.touches[0].clientX;
      yUp = e.touches[0].clientY;
      xDiff = this.xDown - xUp;
      yDiff = this.yDown - yUp;
      if (Math.abs(xDiff) > Math.abs(yDiff)) {
        if (xDiff > 0) {
          this.next.click();
        } else {
          this.prev.click();
        }
      }
      this.xDown = null;
      this.yDown = null;
    };

    return Swipe;

  })();

}).call(this);
